API-Must-be-Swagger-2: 
  description: 'API Must be [Swagger] 2.0 Standard'
  oas: all
  severity: critical
  enabled: true
  rule: 
    Path: $.swagger
    type: match
    options: 
      match: ^2\.\d*$
